### ISSUE TITLE
Expose Socket._client.Client.RemoteEndPoint

### ISSUE THREAD

**Issue by ryanwilliams83** [mode51/Tungsten#1]
Please expose the client port number and consider changing Socket.Name to include the client port number.

// FinalizeConnection(_client.Client.RemoteEndPoint.As<IPEndPoint>()?.Address);

Only the Address portion of the IPEndPoint is passed into FinalizeConnection.

**Comment by mode51** [comment]
Those are good ideas Ryan.  I'll start working on it.  I'll remove the Guid from the Name too; that was actually just for testing and I forgot to remove it.

**Comment by mode51** [comment]
I've exposed the IPEndPoint through a new Socket.RemoteEndPoint readonly property.  The remote Port is available via this property.  

I changed the Connected multi-cast delegate from IPAddress to IPEndPoint.

I added the remote IPEndPoint to the Disconnected multi-cast delegate.

I corrected the Name property; it should show something like "127.0.0.1:5150" now.

Do these changes work for you?

**Comment by mode51** [comment]
Do you need the NuGet package updated with this change?

**Comment by mode51** [comment]
I went ahead and published Tungsten.Net v1.2.3.4 with the changes.

**Comment by ryanwilliams83** [comment]
Sorry for my late reply, Thanks for making these changes.

**Comment by mode51** [comment]
No worries, thanks for the input.
