### ISSUE TITLE
SecureStringClient does not reset _remotePublicKey on Disconnect

### ISSUE THREAD

**Issue by ryanwilliams83** [mode51/Tungsten#2]

**Comment by mode51** [comment]
Thanks.  I'll look into this.

**Comment by mode51** [comment]
This should be fixed now.  I added the following to the SecureStringClient constructor.

Disconnected += (socket, remoteEndPoint, e) =>
{
    _remotePublicKey = null;
};

**Comment by mode51** [comment]
Do you need the NuGet package updated with this change?

**Comment by mode51** [comment]
I went ahead and published Tungsten.Net v1.2.3.4 with the change.
